language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: uIjk0Owt4DNThzse0ce8kJpH3+rW42jUFGQlJoPUwqgimkSxcMGrgbDTrA+CZrveZxLCllOKl9aMKEkYuiwIhTQyqc3jHgH3RQrwr8BTxfwhTUvQEmPXzPL+q1hpHedRKsBRLmc1tDCv5k8Jg/ABIgoTraE1y8fRkELLuEM+6Zb524rQLf0cwAU17U1owLtuBv4xgBHncSHEeWsIP83MLnDFKD0L9bjm17PDdxqomwCuhlz7v6bWZ9WkrjbweN2XWP5Z+tYRGzIGhWgZGxTv1IXqQHHm8VGdZhyAfkPR9UdUI9/7nVirlDRqVJpU5MgWDwEDdt3VqlVmhoGJlCRk1q2z6sOYlJKR8/nBp4iWJc1MUfX+BQAOWndFRp3amKeOpsawcSlvlYgvjXjk4HG2mMaYn+xzxCDmnRU38ty5xFG07SFVS/6vhrykvnWmg/RXT5SB1T5AWsmuXfUP2DtghsXxmBfa6puvBRr0KqTmdA9BKAlDBBqW5VBlZ9KQPgN604AzdE2Bq+LPBO/mDUaMXVdG7N1qqg/N1utmyhI096n+uh0VWEmKPUpY2h+nBWHN6UctJsn6fzQW99DvIU8JFGHyZ9MxLnS3Nreit/lL4yi5Sp5jp1TaDR7uYaAEzC8/JIwBbA56G99T/rskmIBJOKgxTdl8dgiWTDJVwgV8Au8=
  - secure: abxA+OP3/JuK7X9zUXJgtmvIIM4ywJMCi12ZQJessMmKcl8UeZMoVpKtsdMQU0H+sWWhdAf5V6ywCDHBMHj0+v52CA4jKBG2BhPQqGu7WRhcFrwHeEWhG2IpmaX065lgFNjhs0lJvKpZL3wfKEL7fnz5lERAYffKCn7nuezBEAl0UasN4v6Uzl01ce49ddpyz+Eqbm7JFhQ4YyObCx8q2OsAT1arkj18wYcUmu+6FF1uVRVgP51AoCb4086IJ+kUAuDUJgNge4HoTv+jgyPK3PY6eHzKP58sJQyyb05NF8S/1vrPoerVGVOvDNTMr6cB89EgZ2cExKNlvyUyWJiC3s10McVzosyEl/jL8rjpdi1ax/xBYSMZnMZ3vJz5jW2lVpUiiSIn25JIuZhYAOkWGLh6gSbp5f4ePbGXYThaYqZ6Qov0Os7goIT9zOQ7NtVLB/AfxMteywsgPJasZqy/wi4VbcYvCMxlETNxvIPoB72Pgpn7BI69Yx7/TUPwoM0c9m2W8hHAvHj6UWgI2Y7gx2hiLo2CYSR9bd8KKu5QXwHZXoNKRsMsquYka4UEk6Oms3NoalGe0WHmZI8CocU5RDEx/fhMWbc7uXIgebRfnmoI90BDKFeRhu+Is1iw9XEushZRZx6qxU3wZwnhgvO6FlYLGfkgpeXogiw8sASziEk=
