language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: ncrd2TmvY/lPDW7C4z18iIDAK8seANbCtQUUx1lQ2kmtVByiIQsOZNaYWHmu7wSgMOmjC3jsw035LxBA/8j9SW8YpefL8nPXu4Cr9HzFS0cj/TR8i43FF4m8Km5z+cM2zn0KmLLAuJoVg+Il7U7KrM1iHDk1+DNFm3yKICyDaav6NFqCO7TVt0qbljlyxwYIhtmnF8N83uS599FazrujfcMb6C/giS5kc8Yut/UZts9lh+imBg5Sd5e/jPrMIyxtUkaOJLEhlEv0sjjFYw1RwlUYOz4/4TZPIkog/WRJc8jWBE9cg6YKrf/c1BTVYdM0hCMO/V2QJI0C8xYeWFK/piwjcIYYiMxjHVOSdMsK5+PivlhUb2Jc67v5IIkLvV33wLiNrW0+ctrB/D5p+Qetny0yRfkatdUFvrU+fR38+AQaRrTFyvPQMxIZSxXNH1XJyCxQYcK2DFzEy1BFQvCQ2VVwis92VY/1x3vCEgztHVyBrUyf6Jj5TRP7jqanniQV79/usJFh2rZr4LTmwi7KCv8QFV5tj0k1KYvuX12RW8BIV6aXdt2qksr3M+ARxyD1EG0SA9RukPS781klpezaGTv4elqKGpSPBdtk+l1alNBHAez4OeIdHjISLLMzh7xxzPs4jAGOdmwRTRkFLXQKJ2KF7+gLZpxGMcVQeAJb9YI=
  - secure: Gvd6k5BfAcyAA5T1ZvVHG8OAk3NvLE5fp10IpIb8ZSpgF4Sw8qZBuDdzADUBYTsauVF5gklupwXdIhd/1BdCYKgGUwWafZQPaMyA7B9Q3mOaI/+pgKfFfD1iPtrLhi/4DgmV+RXM5o36fD69xV8jesfRt864C1qWjgMwglRY1uzev9/frlZP+o6cXd65cd+9bBYY3fdZS4ctoJfcjszoXYBCPdiP0t/ToEcbKVB7lOpkp0lrSBCH7hGGTqVJR3U/4+3jWQKVemfAKunj6bS6ZBFHniCC1wWaNK0mVYvBgLZLmP0NJo4XxcCicodHO6b+Wk7b8xZEYqwXmBh5hYCPKK08ZmRfYcI2WoZaMYnLgWodd68sxy7xTz9CdwcCn64ye92m/acmqjHLmtjkl3RNZ/9p950LU/Z1iFbnuoRd9XqrMSOE46pEIw/nkRCL+mKIO9TgJ29YZgfGN+hcK/fgSdLFG2xE7fv05/I9zzBhjUx+VIx0hoffM91pVS1RQUTtiRocJDjCCwuhiYvUogi6kpPoee2hWn21NqBju4UP9jZCDOs2jFYSwR/tInbgaqG3rDrudtquk0WaRzHzGX8tEZLVB+TqzsBzYZV7x2RxoN0OJIAcK0fTPAwA0ekK3sbMMswgV49sU2a6q3AyvRFgYim+nuOh1awEDqheqd4copo=
